name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-package-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Zip Lambda function
        run: zip -r function.zip lambdas/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: lambda-package
          path: function.zip

  deploy:
    needs: build-and-package-lambda
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: lambda-package
          path: .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve

